---

- name: enviar o resolv.conf
  hosts: all
  tasks:
   - name: Copiando o resolv
     copy:
      src: resolv.conf
      dest: /etc/resolv.conf

- name: instalando os pacotes
  hosts: devops docker
  tasks:
   - name: Instalar o pacote vim
     apt:
      name: vim
      state: present
  
   - name: instalando htop
     apt: name=htop state=present

      
