---

- name: instalando apache e php no centos
  yum:
   name: "{{item}}"
   state: present
  with_items:
   - httpd
  when: ansible_os_family == "RedHat"

- name: verificando se o apache e o php esta habilitado
  service:
   name: "{{item}}"
   state: started
  with_items:
   - httpd
  when: ansible_os_family == "RedHat"


- name: parando o firewalld
  service:
   name: firewalld
   state: stopped
  when: ansible_os_family == "RedHat"
